---

# Distribute SSH keys
# hosts: nullHost
# vars:
#     ssh_key: '~/.ssh/id_rsa/'
#     tasks:
#         - name: copy ssh key
#             authorized_key:
#                 key: "{{ lookup('file', ssh_key) }}"
#             user: root 

# Install Raspberry Pi Print Server Software
- hosts: dads_rpi
  become: true
  tasks:

  - name: Install HPLIPS
    apt:
      name: hplip

  - name: Install CUPS
    apt:
      name: cups
      state: latest
  
  - name: Add pi to ipadmin group
    shell: "usermod -a -G lpadmin pi"

  - name: Set cupsctl to allow traffic
    shell: "cupsctl --remote-any"

  - name: Restart cups
    shell: "/etc/init.d/cups restart"
  
  - name: Install Samba
    apt:
      name: samba
      state: latest
  
  - name: Restart SAMBA
    shell: "/etc/init.d/samba restart"

# Install Sane (Scanner)
  - name: Install Scanner 
    apt:
      name: sane

  - name: Change Run to yes
    - lineinfile:
      path: /etc/default/saned
      regexp: '^RUN='
      line: 'RUN=yes'

  - name: Change Run to yes
    - lineinfile:
      path: /etc/sane.d/saned.conf
      line: '192.168.1.0/24'

  - name: Change Run to yes
    - lineinfile:
      path: /etc/sane.d/saned.conf
      regexp: '#data_portrange = 10000 - 10100'
      line: 'data_portrange = 10000 - 10100'

  - name: Adding existing user 'pi' to group pl
    user:
      name: 'pi'
      groups: pl
      append: yes

  - name: Start saned service
    shell:
    - 'service saned restart'
    - update-rc.d saned defaults

  

      


