---

all:
  hosts:
    rpi:
      ansible_ssh_host: 192.168.1.117
      ansible_ssh_user: "pi"
      ansible_ssh_pass: "milton"
    dads_rpi:
      ansible_ssh_host: 192.168.1.83
      ansible_ssh_user: "pi"
      ansible_ssh_pass: "omlpieap1"
    nullHost:
      ansible_ssh_host: 1.2.3.4